# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 11badc14b20851c30fcf56bc0980fbc89f69a93e27eab2b524e0bd8995e4a3431bf59694845601774c77270bdcf9d59821a82d222f0458a83fb3744592939601

test:
  secret_key_base: b2537afd1baf88d4302f3b2d0e1d9e00792718ff5762eb6662ac3473a05e7da9177ca802df860cdb15bf904f542b8a5db2964db3d3b3aa36935ab3246e20d575

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
